on:
  schedule:
    - cron: 0 8 6,12,18,24 * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOURCE_REPOSITORY: shuwariafrica/container-images

jobs:

  build-el9-jdk-image:
    name: "Build and/or Publish OL9 Java Development Image"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ "20.0.1", "17.0.7" ]
      fail-fast: false
    env:
      IMAGE: shuwariafrica/el9-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}

      - name: JDK Meta
        id: jdk-meta
        run: |
          echo "java-major-version=$(echo ${{ matrix.java-version }} | awk -F '.' '{print $1}')" >> ${GITHUB_OUTPUT}

      - name: Build JDK ${{ matrix.java-version }}
        id: publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: el9.jdk.Dockerfile
          push: ${{ (github.event_name != 'pull_request') && (github.repository == env.SOURCE_REPOSITORY) }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: JDK_VERSION=${{ matrix.java-version }}
          tags: |
            ${{ env.IMAGE }}:${{ steps.jdk-meta.outputs.java-major-version }}
            ${{ env.IMAGE }}:${{ matrix.java-version }}.${{ github.run_number }}
